### PR TITLE
quick transfer from the email chain

### PR DESCRIPTION
**Pull request by VaclavK**
WIP - feel free to commit against this

### CODE REVIEW

**Comment by VaclavK** [comment]
if any code comment etc. is added, version will have to be bumped

**Comment by djfr** [comment]
I would actually put in two separate controller sets: one being `V1` and the other being `V2` and set both routings and swashbuckle specs for all versions.

**Comment by VaclavK** [comment]
@djfr if I understand you correctly you would bypass asp.net api versioning and DIY the routes etc...?

**Comment by VaclavK** [comment]
spoke to @djfr , the suggestion is to implement v2 controller sample as a code and set the attributes etc... but have code rather than just "text" - drawback - they may not delete it...

**Comment by arturek** [comment]
@VaclavK they might be marked with Obsolete to trigger an error when left unchanged.

**Comment by VaclavK** [comment]
@arturek that and throwing an exception should do the trick - agreed

**Comment by djfr** [comment]
@VaclavK Can we merge this one? It's down to purely a README change and it's been lingering since April!

**Pull request merged**
